import http from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { responseFixture } from './fixtures.mjs';
const { chromium } = createRequire(import.meta.url)(process.argv[2]);
const out = 'docs/verification/pwa-20260927';
await mkdir(out, { recursive: true });
let mode = 'v1';
const originalSW = await readFile('app/sw.js', 'utf8');
const files = Object.keys(JSON.parse(originalSW.match(/const HASHES = ([\s\S]*?);/)[1]));
const bodies = Object.fromEntries(await Promise.all([...files, 'sw.js'].map(async name => [name, await readFile(`app/${name}`)])));
const hash = body => createHash('sha256').update(body).digest('hex');
const v2html = Buffer.from(bodies['index.html'].toString().replace('<body>', '<body data-release="v2">'));
const v2worker = originalSW.replace(/sun-and-rain-shell-[a-f0-9]+/, 'sun-and-rain-shell-test-v2').replace(hash(bodies['index.html']), hash(v2html));
const server = http.createServer((req, res) => {
  const file = new URL(req.url, 'http://localhost').pathname.slice(1) || 'index.html';
  if (!bodies[file]) { res.writeHead(404); res.end(); return; }
  let body = bodies[file];
  if (mode !== 'v1') {
    if (file === 'index.html') body = v2html;
    if (file === 'sw.js') body = Buffer.from(mode === 'broken' ? v2worker.replace('test-v2', 'test-broken') : v2worker);
    if (mode === 'broken' && file === 'style.css') body = Buffer.from('/* incomplete deployment */');
  }
  res.writeHead(200, { 'Cache-Control': 'no-store', 'Content-Type': file.endsWith('.png') ? 'image/png' : file.endsWith('.css') ? 'text/css' : file.endsWith('.webmanifest') ? 'application/manifest+json' : /\.m?js$/.test(file) ? 'text/javascript' : 'text/html' });
  res.end(body);
});
let browser;
const checks = [], errors = [];
try {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}`;
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: 'allow' });
  let offline = false;
  const setOffline = async value => { offline = value; await context.setOffline(value); };
  await context.route('https://api.open-meteo.com/**', route => offline ? route.abort() : route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(responseFixture(route.request().url().includes('gfs_global') ? 'uvpop' : 'weather', Date.now() / 1000)) }));
  await context.route('https://geocoding-api.open-meteo.com/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ results: [{ name: '札幌市', latitude: 43.06667, longitude: 141.35, country_code: 'JP' }] }) }));
  let page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url);
  await page.waitForFunction(() => document.querySelector('#storage-status').textContent === '端末に保存済み');
  await page.waitForFunction(() => navigator.serviceWorker.controller && document.querySelector('#pwa-status').textContent.includes('準備ができました'));
  const values = await page.locator('.metric-grid').innerText();
  const manifest = await page.evaluate(async () => (await fetch('manifest.webmanifest')).json());
  assert.equal(manifest.display, 'standalone'); assert.equal(manifest.icons.length, 2);
  checks.push('first install, complete shell and manifest');
  await page.getByRole('button', { name: '地点を変更', exact: true }).click();
  await page.getByLabel('地名', { exact: true }).fill('札幌市');
  await page.getByRole('button', { name: '検索', exact: true }).click();
  await page.locator('.location-candidate').click();
  await page.getByRole('button', { name: 'この地点に変更', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#location-name').textContent.includes('札幌市') && !document.querySelector('#refresh').disabled && document.querySelector('#storage-status').textContent === '端末に保存済み');
  await setOffline(true);
  await page.reload();
  await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
  assert.equal(await page.locator('.metric-grid').innerText(), values);
  assert((await page.locator('#location-name').textContent()).includes('札幌市'));
  assert(await page.locator('#connection-status').isVisible());
  assert((await page.locator('#source-status').textContent()).includes('以前の取得値'));
  assert.notEqual(await page.locator('#request-status').textContent(), '予報を取得しました。');
  await page.getByRole('button', { name: '次の時間' }).click();
  assert.equal(await page.locator('.metric .no-data').count(), 0);
  await page.screenshot({ path: `${out}/pwa-offline-390.png`, fullPage: true });
  await page.close();
  page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url); await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
  assert.equal(await page.locator('.metric-grid').innerText(), values);
  checks.push('browser offline reload and closed-page restart with saved forecast');
  await setOffline(false);
  mode = 'broken';
  await page.evaluate(async () => {
    const reg = await navigator.serviceWorker.getRegistration();
    window.failedInstall = false;
    reg.addEventListener('updatefound', () => { const worker = reg.installing; worker.addEventListener('statechange', () => { if (worker.state === 'redundant') window.failedInstall = true; }); }, { once: true });
    await reg.update();
  });
  await page.waitForFunction(() => window.failedInstall);
  assert.equal(await page.evaluate(async () => (await navigator.serviceWorker.getRegistration()).waiting === null), true);
  await setOffline(true); await page.reload();
  assert.equal(await page.locator('body').getAttribute('data-release'), null);
  checks.push('mixed deployment rejected; old release still starts offline');
  await setOffline(false); mode = 'v2';
  await page.evaluate(async () => (await navigator.serviceWorker.getRegistration()).update());
  await page.waitForFunction(async () => !!(await navigator.serviceWorker.getRegistration()).waiting);
  assert.equal(await page.locator('body').getAttribute('data-release'), null);
  await page.waitForFunction(() => !document.querySelector('#pwa-update').hidden);
  const cachesBefore = await page.evaluate(() => caches.keys());
  assert(cachesBefore.some(key => key.endsWith('test-v2')));
  checks.push('complete update waits without replacing open document');
  await page.close();
  page = await context.newPage();
  await page.goto(url);
  await page.waitForFunction(() => document.body.dataset.release === 'v2');
  await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
  assert((await page.locator('#location-name').textContent()).includes('札幌市'));
  assert.equal(await page.locator('.metric-grid').innerText(), values);
  const cachesAfter = await page.evaluate(() => caches.keys());
  assert.deepEqual(cachesAfter, ['sun-and-rain-shell-test-v2']);
  const cachedURLs = await page.evaluate(async () => (await (await caches.open('sun-and-rain-shell-test-v2')).keys()).map(r => r.url));
  assert(cachedURLs.every(value => new URL(value).origin === new URL(url).origin));
  await setOffline(true); await page.reload();
  assert.equal(await page.locator('body').getAttribute('data-release'), 'v2');
  checks.push('close/reopen adopts new shell; forecast survives; old shell removed; no API cache');
  await context.close();
  const emptyContext = await browser.newContext({ serviceWorkers: 'allow' });
  await emptyContext.route('https://api.open-meteo.com/**', route => route.abort());
  const emptyPage = await emptyContext.newPage();
  await emptyPage.goto(url);
  await emptyPage.waitForFunction(() => navigator.serviceWorker.controller && document.querySelector('#pwa-status').textContent.includes('準備ができました'));
  await emptyContext.setOffline(true); await emptyPage.reload();
  await emptyPage.waitForFunction(() => !document.querySelector('#refresh').disabled);
  assert.equal(await emptyPage.locator('.metric .no-data').count(), 4);
  assert((await emptyPage.locator('#request-status').textContent()).includes('取得できませんでした'));
  checks.push('prepared shell without saved forecast shows missing values, not zeros');
  await emptyContext.close();
  const cold = await browser.newContext({ offline: true });
  const coldPage = await cold.newPage();
  await assert.rejects(coldPage.goto(url), /ERR_INTERNET_DISCONNECTED/);
  checks.push('first-ever offline visit cannot install or fabricate a forecast');
  await cold.close();
  assert.deepEqual(errors, []);
  await writeFile(`${out}/results.json`, JSON.stringify({ browser: browser.version(), checks, errors, networkOffline: 'BrowserContext.setOffline', forecastAPI: 'mocked', updateServer: 'test server with changed HTML, hashes and worker' }, null, 2));
  console.log(`PASS: ${checks.length} PWA lifecycle scenarios`);
} finally { await browser?.close(); await new Promise(resolve => server.close(resolve)); }
