// Generated by scripts/build-sw.mjs. Rebuild after changing any shell asset.
const CACHE = 'sun-and-rain-shell-7cacf7512ff84c23';
const HASHES = {
  "index.html": "48f159b346b41bab6cfc936e18e47897f8d1e0b17260e454e9a6bdfdbca65383",
  "style.css": "87685416ded1e7446724b8f0ec646497b5df30166140d5e11841847d0ccf235a",
  "app.mjs": "0df4ce0f9c072594203994c85702a397850f1ccc983837e6c09b008339531f27",
  "weather.mjs": "2f0e5883ea6ff84de92f398a0a74c783f59782849a5976babca0fc1737ba0cef",
  "comparison.mjs": "a0da573af49fec7b136139e54fdd5e750018f90e6ca8c80f9f6e6086d357f7df",
  "storage.mjs": "860785dc212625d266f09f372ea9854665ca255145e154d70d4c8af80299d990",
  "location.mjs": "5fec799ddfc24c0273126faa94a0f82c30749109bbcabdb39ba9b804c29252c6",
  "cities.json": "fe91f3c5736b94e3002024a2e1b398ec836ff0649be32e783cf466470481792e",
  "pwa.mjs": "410b56ac589b51943585485699d907877481acf2661c5c67e33c9aaba07e9132",
  "manifest.webmanifest": "18fd2ace66d6628c0c7f079e9b20c00edecef574fdf0bb16d848aaa2b59f33b6",
  "icon-192.png": "75cb3fcbfc25d5a39c6968da99785f951b887a2e2488c0122eb7c0f7fe7be913",
  "icon-512.png": "3dd539b9c77f0fa131c91f1bac00405667c76b5bae4b866c5074d49db22a7cd0",
  "apple-touch-icon.png": "dc7620322deaeb7db9e326807e58dfd4e464bb0c0ced8e1a45fa92aa1b09eb4c"
};
const base = new URL('./', self.location.href);
// Fetch the canonical root document; static hosts may redirect /index.html.
const urlFor = file => new URL(file === 'index.html' ? './' : file, base).href;
self.addEventListener('install', event => event.waitUntil((async () => {
  try {
    const responses = await Promise.all(Object.entries(HASHES).map(async ([file, expected]) => {
      const response = await fetch(urlFor(file), {cache: 'reload'});
      if (!response.ok || response.redirected) throw new Error('Missing shell asset');
      const bytes = await response.clone().arrayBuffer();
      const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), b => b.toString(16).padStart(2, '0')).join('');
      if (hash !== expected) throw new Error('Mixed release assets');
      return [file, response];
    }));
    const cache = await caches.open(CACHE);
    await Promise.all(responses.map(([file, response]) => cache.put(urlFor(file), response)));
  } catch (error) { await caches.delete(CACHE); throw error; }
})()));
// No skipWaiting: an update takes over after all existing app pages close.
self.addEventListener('activate', event => event.waitUntil((async () => {
  for (const key of await caches.keys()) if (key.startsWith('sun-and-rain-shell-') && key !== CACHE) await caches.delete(key);
  await self.clients.claim();
})()));
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const file = url.pathname.slice(base.pathname.length);
  const target = event.request.mode === 'navigate' && (file === '' || file === 'index.html') ? 'index.html' : file;
  if (!Object.hasOwn(HASHES, target)) return;
  event.respondWith((async () => {
    const cached = await (await caches.open(CACHE)).match(urlFor(target));
    if (cached) return cached;
    // A missing cached file must still match this release before being used.
    const response = await fetch(urlFor(target), {cache: 'reload'});
    const bytes = await response.clone().arrayBuffer();
    const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), b => b.toString(16).padStart(2, '0')).join('');
    if (!response.ok || response.redirected || hash !== HASHES[target]) return new Response('App update required', {status: 503});
    await (await caches.open(CACHE)).put(urlFor(target), response.clone());
    return response;
  })());
});
self.addEventListener('message', event => {
  if (event.data?.type !== 'STATUS' || !event.ports[0]) return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const ready = (await Promise.all(Object.keys(HASHES).map(file => cache.match(urlFor(file))))).every(Boolean);
    event.ports[0].postMessage({ready, version: CACHE});
  })());
});
