import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const root = new URL('../app/', import.meta.url);
const files = ['index.html', 'style.css', 'app.mjs', 'weather.mjs', 'comparison.mjs', 'storage.mjs', 'location.mjs', 'cities.json', 'pwa.mjs', 'manifest.webmanifest', 'icon-192.png', 'icon-512.png', 'apple-touch-icon.png'];
const digest = bytes => createHash('sha256').update(bytes).digest('hex');
const hashes = Object.fromEntries(await Promise.all(files.map(async file => [file, digest(await readFile(new URL(file, root)))])));
const version = digest(JSON.stringify(hashes) + await readFile(new URL(import.meta.url), 'utf8')).slice(0, 16);
const worker = `// Generated by scripts/build-sw.mjs. Rebuild after changing any shell asset.
const CACHE = 'sun-and-rain-shell-${version}';
const HASHES = ${JSON.stringify(hashes, null, 2)};
const base = new URL('./', self.location.href);
// Fetch the canonical root document; static hosts may redirect /index.html.
const urlFor = file => new URL(file === 'index.html' ? './' : file, base).href;
self.addEventListener('install', event => event.waitUntil((async () => {
  try {
    const responses = await Promise.all(Object.entries(HASHES).map(async ([file, expected]) => {
      const response = await fetch(urlFor(file), {cache: 'reload'});
      if (!response.ok || response.redirected) throw new Error('Missing shell asset');
      const bytes = await response.clone().arrayBuffer();
      const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), b => b.toString(16).padStart(2, '0')).join('');
      if (hash !== expected) throw new Error('Mixed release assets');
      return [file, response];
    }));
    const cache = await caches.open(CACHE);
    await Promise.all(responses.map(([file, response]) => cache.put(urlFor(file), response)));
  } catch (error) { await caches.delete(CACHE); throw error; }
})()));
// No skipWaiting: an update takes over after all existing app pages close.
self.addEventListener('activate', event => event.waitUntil((async () => {
  for (const key of await caches.keys()) if (key.startsWith('sun-and-rain-shell-') && key !== CACHE) await caches.delete(key);
  await self.clients.claim();
})()));
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const file = url.pathname.slice(base.pathname.length);
  const target = event.request.mode === 'navigate' && (file === '' || file === 'index.html') ? 'index.html' : file;
  if (!Object.hasOwn(HASHES, target)) return;
  event.respondWith((async () => {
    const cached = await (await caches.open(CACHE)).match(urlFor(target));
    if (cached) return cached;
    // A missing cached file must still match this release before being used.
    const response = await fetch(urlFor(target), {cache: 'reload'});
    const bytes = await response.clone().arrayBuffer();
    const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)), b => b.toString(16).padStart(2, '0')).join('');
    if (!response.ok || response.redirected || hash !== HASHES[target]) return new Response('App update required', {status: 503});
    await (await caches.open(CACHE)).put(urlFor(target), response.clone());
    return response;
  })());
});
self.addEventListener('message', event => {
  if (event.data?.type !== 'STATUS' || !event.ports[0]) return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const ready = (await Promise.all(Object.keys(HASHES).map(file => cache.match(urlFor(file))))).every(Boolean);
    event.ports[0].postMessage({ready, version: CACHE});
  })());
});
`;
if (process.argv.includes('--check')) {
  if (await readFile(new URL('sw.js', root), 'utf8') !== worker) throw new Error('sw.js is stale. Run node scripts/build-sw.mjs');
} else await writeFile(new URL('sw.js', root), worker);
console.log(`Shell ${version}: ${files.length} assets`);
